name: main
permissions:
  contents: write
  pull-requests: write
  issues: write
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate:
    strategy:
      matrix:
        example:
          - simple
    name: validate
    runs-on: ubuntu-26.04
    steps:
      - name: "Pretend you're me"
        run: sudo mkdir -p /home/becker/.ssh
      - name: "Generate a SSH Key"
        run: ssh-keygen -t rsa -b 4096 -f /home/becker/.ssh/id_rsa -q -N ""
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Dev tools
        uses: jdx/mise-action@v5
        with:
          install: true
      - name: Start Consul
        run: nohup consul agent -dev & sleep 3
      - name: Init terraform
        run: terraform -chdir=examples/${{ matrix.example }} init
      - name: Validate terraform
        run: terraform -chdir=examples/${{ matrix.example }} validate
  release:
    needs:
      - validate
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Build Env
        uses: jdx/mise-action@v5
        with:
          install: true
        env:
          MISE_ENV: release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MISE_ENV: release
        run: npx semantic-release
